<?xml version="1.0" encoding="utf-8"?><Database Name="VehicleDB" Class="VehicleDBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(localdb)\MSSQLLocalDB;Initial Catalog=VehicleDB;Integrated Security=True;Connect Timeout=30;Encrypt=False;TrustServerCertificate=False" SettingsObjectName="vehicle.repository.Properties.Settings" SettingsPropertyName="VehicleDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Service" Member="Services">
    <Type Name="Service">
      <Column Name="ServiceID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Cost" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="VehicleID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.VehicleRegister" Member="VehicleRegisters">
    <Type Name="VehicleRegister">
      <Column Name="VehicleID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PlateNo" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Model" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Brand" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="VehicleType" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ServiceWeight" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="DateInTrafficFirstTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ServiceIsBooked" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="YearlyFee" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>